import './globals.css'
import { Inconsolata } from 'next/font/google'
import Header from './components/Header/Header'

const inter = Inconsolata({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
