"use client";
import React, { useState, useEffect } from 'react';
import styles from './page.module.css'
import OpeningText from './components/OpeningText/OpeningText'
import LearnMoreButton from './components/LearnMoreButton/LearnMoreButton'

export default function Home() {
  // This piece of state and UseEffect were generated by GTP-4 so I am keeping
  // the somewhat unnecessary comments for self-reference

  const [windowHeight, setWindowHeight] = useState(undefined);

  useEffect(() => {
    const handleResize = () => {
      console.log(window.innerHeight)
      setWindowHeight(window.innerHeight);
    };

    // Attach the event listener
    window.addEventListener('resize', handleResize);

    handleResize();

    // Clean up the event listener when the component is unmounted
    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, []); // Empty array prevents errors!

  const containerStyles = {
    height: `${windowHeight * 0.8}px`,
  }

  return (
    <main>
      <div style={containerStyles} className={styles.container}>
        <OpeningText />
        <iframe className={styles.homeGraphic} width="446" height="317" seamless frameBorder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQM2aZd61dMcmqW3tL_ISD3HO46ElesE-DKvzRQAu0NpaiNCNQ6E19O78mnyasZVwuwD7q0pzSqnkua/pubchart?oid=213546913&amp;format=interactive"></iframe>
      </div>
      <div className={styles.homePageBottom}>
        <LearnMoreButton />
      </div>
    </main>
  )
}
