"use client";
import React, { useState, useEffect } from 'react';
import styles from './page.module.css'
import OpeningText from './components/OpeningText/OpeningText'
import LearnMoreButton from './components/LearnMoreButton/LearnMoreButton'

export default function Home() {
  // This piece of state and UseEffect were generated by GTP-4 so I am keeping
  // the somewhat unnecessary comments for self-reference
  const [windowHeight, setWindowHeight] = useState(window.innerHeight);

  useEffect(() => {
    console.log(windowHeight)
    const handleResize = () => {
      setWindowHeight(window.innerHeight);
    };

    // Attach the event listener
    window.addEventListener('resize', handleResize);

    // Clean up the event listener when the component is unmounted
    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, [windowHeight]); // GTP-4 made an error here -> array should not be empty


  const containerStyles = {
    height: `${windowHeight * 0.8}px`,
  }

  return (
    <main>
      <div style={containerStyles} className={styles.container}>
        <OpeningText />
        <img className={styles.homeGraphic} src="temp.png"></img>
      </div>
      <div className={styles.homePageBottom}>
        <LearnMoreButton />
      </div>
    </main>
  )
}
